block_alert:
- "DIAMOND_ORE"

messages:
  reloaded: "&aPlugin Sanction reload"
  help: "&e/ss <player>"
  not_found: "&c%arg% n'est pas un joueur valide."
  no_touch: "&cCe joueur ne peux recevoir de sanction de votre part."
  select: "&aSanction&7: %name%."
  applied: "&6Sanction appliqué à &c%name% !"
  category:
    inv_name: "Menu | Joueur %name%"
  sanction_player:
    inv_name: "Menu | %type% %name%"
  main:
    inv_name: "Sanction de %name%"
  confirm:
    inv_name: "Confirmer la sanction de %name%"
  report:
    inv_name: "Signalement de %name%"
    help: "/report <pseudo> : Ouvre l'interface de signalement d'un joueur"
    alert: "&d%name% &ea signalé &c%cible% &epour &7%reason%"
  teleport:
    no_one: "Personne à qui se téléporter."
    go: "&aTéléportation à &6%name%"
  staffmode:
    enabled: "&aActivation du mode staff"
    disabled: "&cDésactivation du mode staff"
  spec:
    survival: "&aVous êtes désormais en &esurvie"
    spec: "&aVous êtes désormais en &dspéctateur"
permissions:
  admin: sanction.command.manager
  no_tp: sanction.use

back-item:
  material: OAK_DOOR
  name: "&cRetour"

main:
  items:
    head:
      material: PLAYER_HEAD
      name: "&a%name%"
      lore:
      - "&7Clic pour find"
      command: "find %name%"
      proxy: true
    sanctions:
      material: ENCHANTED_BOOK
      name: "&aSanction"
      lore:
      - "&7Sanctionner le joueur"
    dupeip:
      material: NAME_TAG
      name: "&aDupeip"
      lore:
      - "&7Dupeip le joueur"
      command: "dupeip %name%"
      proxy: false
    history:
      material: BOOK
      name: "&aHistorique"
      lore:
      - "&7Voir l'historique du joueur"
      command: "history %name%"
      proxy: false
    teleport:
      material: COMPASS
      name: "&aTéléportation"
      lore:
      - "&7Se téléporter au joueur"
      - ""
      - "&cAttention: Soyez bien en vanish AVANT de vous TP"
      command: "teleport %name%"
      proxy: false
      as_player: true
    bell:
      command: "mycmd"
      material: BELL
      name: "&aMa cmd"
      lore:
      - "&7Lancement de mycmd"
      command: "mycmd"
      proxy: false
confirm:
  items:
    confirm:
      material: LIME_WOOL
      name: "&aConfirmer"
      lore:
      - "&7Cliquez pour confirmer"
    cancel:
      material: RED_WOOL
      name: "&aAnnuler"
      lore:
      - "&7Cliquez pour annuler"

kick:
  items:
    main:
      material: STICK
      name: "Kick"
      lore:
      - "&7Options pour kick le joueur"
mute:
  items:
    main:
      material: PAPER
      name: "Mute"
      lore:
      - "&7Options pour mute le joueur"
  actions:
    1:
      slot: 10
      name: "&cInsulte"
      lore:
      - "&7Mute pour 2h pour insulte"
      command: "mute %name% 2h Insulte --sender-uuid=%executor_uuid% --sender=%executor%"
      permission: "sanction.mute"
    2:
      slot: 11
      name: "&cMenace de mort"
      lore: "&7Mute pour menace de mort"
      command: "ban %name% incrr --sender-uuid=%executor_uuid% --sender=%executor%"
      permission: "sanction.mute"
ban:
  permission: "sancton.use.bans"
  items:
    main:
      material: BOOK
      name: "Ban"
      lore:
      - "&7Options pour ban le joueur"
  actions:
    1:
      slot: 10
      name: "Ban test"
      lore: "Incroyable ban"
      command: "ban %name% incrr"
      permission: "sanction.ban"
    2:
      slot: 11
      name: "Ban 2"
      lore: "Incroyable ban"
      command: "ban %name% incrr"
      proxy: false
      permission: "sanction.ban2"
report:
  actions:
    1:
      slot: 10
      name: "Spam"
      lore: "&7Spam dans le chat"
      reason: "Spam"
    2:
      slot: 11
      name: "Cheat"
      lore: "&7Cheat en jeu"
      reason: "Cheat"

staffmode:
  items:
    inventory:
      material: PAPER
      name: "Voir l'inventaire"
    sanction:
      material: ENCHANTED_BOOK
      name: "Sanctionner"
    teleport_random:
      material: COMPASS
      name: "Téléportation aléatoire"