messages:
  reloaded: "&aPlugin Sanction reload"
  help: "&e/ss <player>"
  not_found: "&c%arg% n'est pas un joueur valide."
  no_touch: "&cCe joueur ne peux recevoir de sanction de votre part."
  select: "&aSanction&7: %name%."
  applied: "&6Sanction appliqué à &c%name% !"
  category:
    inv_name: "Menu | Joueur %name%"
  sanction_player:
    inv_name: "Menu | %type% %name%"
  main:
    inv_name: "Sanction de %name%"

permissions:
  admin: sanction.command.manager"

back-item:
  material: OAK_DOOR
  name: "&cRetour"

main:
  items:
    head:
      material: PLAYER_HEAD
      name: "&a%name%"
      lore:
      - "&7Clic pour find"
      command: "find %name%"
      proxy: true
    sanctions:
      material: ENCHANTED_BOOK
      name: "&aSanction"
      lore:
      - "&7Sanctionner le joueur"
    dupeip:
      material: NAME_TAG
      name: "&aDupeip"
      lore:
      - "&7Dupeip le joueur"
      command: "dupeip %name%"
      proxy: false
    history:
      material: BOOK
      name: "&aHistorique"
      lore:
      - "&7Voir l'historique du joueur"
      command: "history %name%"
      proxy: false
    teleport:
      material: COMPASS
      name: "&aTéléportation"
      lore:
      - "&7Se téléporter au joueur"
      - ""
      - "&cAttention: Soyez bien en vanish AVANT de vous TP"
      command: "teleport %name%"
      proxy: false
      as_player: true
    bell:
      command: "mycmd"
      material: BELL
      name: "&aMa cmd"
      lore:
      - "&7Lancement de mycmd"
      command: "mycmd"
      proxy: false

kick:
  items:
    main:
      material: STICK
      name: "Kick"
      lore:
      - "&7Options pour kick le joueur"
mute:
  items:
    main:
      material: PAPER
      name: "Mute"
      lore:
      - "&7Options pour mute le joueur"
  actions:
    1:
      slot: 10
      name: "&cInsulte"
      lore:
      - "&7Mute pour 2h pour insulte"
      command: "mute %name% 2h Insulte --sender-uuid=%executor_uuid% --sender=%executor%"
      permission: "sanction.mute"
    2:
      slot: 11
      name: "&cMenace de mort"
      lore: "&7Mute pour menace de mort"
      command: "ban %name% incrr --sender-uuid=%executor_uuid% --sender=%executor%"
      permission: "sanction.mute"
ban:
  items:
    main:
      material: BOOK
      name: "Ban"
      lore:
      - "&7Options pour ban le joueur"
  actions:
    1:
      slot: 10
      name: "Ban test"
      lore: "Incroyable ban"
      command: "ban %name% incrr"
      permission: "sanction.ban"
    2:
      slot: 11
      name: "Ban 2"
      lore: "Incroyable ban"
      command: "ban %name% incrr"
      proxy: false
      permission: "sanction.ban2"