block_alert:
  DIAMOND_ORE: "Diamant"

messages:
  reloaded: "&aPlugin Sanction reload"
  help: "&e/ss <player>"
  not_found: "&c%arg% n'est pas un joueur valide."
  no_touch: "&cCe joueur ne peux recevoir de sanction de votre part."
  reported: "&a%name% &7a bien été signalé."
  applied: "&6Sanction appliqué à &c%name% !"
  category:
    inv_name: "Menu | Joueur %name%"
  sanction_player:
    inv_name: "Menu | %type% %name%"
  main:
    inv_name: "Sanction de %name%"
  confirm:
    inv_name: "Confirmer l'action: %name%"
  report:
    inv_name: "Signalement de %name%"
    help: "/report <pseudo> : Ouvre l'interface de signalement d'un joueur"
    alert: "&d%name% &ea signalé &c%cible% &epour &7%reason%"
  teleport:
    no_one: "Personne à qui se téléporter."
    go: "&aTéléportation à &6%name%"
  staffmode:
    enabled: "&aActivation du mode staff"
    disabled: "&cDésactivation du mode staff"
  spec:
    survival: "&aVous êtes désormais en &esurvie"
    spec: "&aVous êtes désormais en &dspéctateur"
  invsee:
    inv_name: "Menu | Inventaire de %name%"
    inv_name_enderchest: "Menu | EnderChest de %name%"
    help: "/invsee <name> : Voir l'inventaire du joueur"
    help_enderchest: "/endersee <name> : Voir l'inventaire de l'end du joueur"
    exp_level: "Niveau d'expérience: %xp%"
    head:
      name: "%name%"
      lore:
      - "&7%ping%ms"
  verifyafk:
    help: "/verifyafk <pseudo> : Vérifier si un joueur est AFK"
    afk: "&6%name% &aest afk."
    not_afk: "&6%name% &dn'est pas afk."
    teleported: "&aTéléporté au warp afk."
    to_warp:
      text: "Téléporter au warp AFK"
      hover: "Cliquez pour téléporter"
    sanction:
      text: "Sanctionner"
      hover: "Cliquez pour sanctionner"
permissions:
  admin: sanction.command.manager
  no_tp: sanction.use
  invsee_interact: sanction.invsee.interact
  endersee_interact: sanction.endersee.interact
  verifyafk_alerts: verifyafk.alerts

back-item:
  material: OAK_DOOR
  name: "&cRetour"

main:
  items:
    head:
      material: PLAYER_HEAD
      name: "&a%name%"
      lore:
      - "&7Clic pour find"
      - "&7"
      - "&7Ping: &6%ping%ms"
      - "&7Loc: &6%loc_x%/%loc_y%/%loc_z%"
      - "&7Client: &6%client%"
      command: "find %name%"
      proxy: true
    head_offline:
      material: PLAYER_HEAD
      name: "&a%name%"
      command: "find %name%"
      proxy: true
    sanctions:
      material: ENCHANTED_BOOK
      name: "&aSanction"
    dupeip:
      material: NAME_TAG
      name: "&aDupeip"
      command: "dupeip %name%"
      proxy: false
    history:
      material: BOOK
      name: "&aHistorique"
      command: "history %name%"
      proxy: false
    teleport:
      material: COMPASS
      name: "&aTéléportation"
      command: "teleport %name%"
      proxy: false
      as_player: true
    bell:
      command: "mycmd"
      material: BELL
      name: "&aMa cmd"
      command: "mycmd"
      proxy: false
confirm:
  items:
    confirm:
      material: LIME_WOOL
      name: "&aConfirmer"
    cancel:
      material: RED_WOOL
      name: "&aAnnuler"

kick:
  items:
    main:
      material: STICK
      name: "Kick"
mute:
  items:
    main:
      material: PAPER
      name: "Mute"
  actions:
    1:
      slot: 10
      name: "&cInsulte"
      command: "mute %name% 2h Insulte --sender-uuid=%executor_uuid% --sender=%executor%"
      permission: "sanction.mute"
ban:
  permission: "sancton.use.bans"
  items:
    main:
      material: BOOK
      name: "Ban"
  actions:
    1:
      slot: 10
      name: "Ban test"
      command: "ban %name% incrr"
      permission: "sanction.ban"
banrsstaff:
  permission: "sancton.use.bans"
  items:
    main:
      material: BOOK
      name: "Ban"
  actions:
    1:
      slot: 10
      name: "Ban test"
      command: "ban %name% incrr"
      permission: "sanction.ban"
report:
  items:
    main:
      material: BOOK
      name: "Ban"
  actions:
    1:
      slot: 10
      name: "Spam"
      lore: "&7Spam dans le chat"
      reason: "Spam"

staffmode:
  items:
    inventory:
      material: PAPER
      name: "Voir l'inventaire"
    sanction:
      material: ENCHANTED_BOOK
      name: "Sanctionner"
    teleport_random:
      material: COMPASS
      name: "Téléportation aléatoire"