messages:
  cs:
    help: "/cs <message>"
    message: "&c(&6%server%&c) -> %name% : &f%message%"
  staffs:
    header:
    - "&f&m-----------------------"
    - "  &7Staff en ligne:"
    line: "&c(&6%server%&c) -> %names%"
    footer:
    - ""
    - "&f&m-----------------------"
  alert_xray: "&c(&6%server%&c) -> &6%name% &ca miné 1 &6%minerai%"


permissions:
  chatstaff: "sanction.cs"
  staffs: "sanction.staffs"
  see_alert_xray: "sanction.xray"