name: SanctionStaff
authors: [Elikill58]
version: 3.0
api-version: 1.13
main: com.elikill58.sanction.spigot.SanctionSpigot
softdepend:
  - InvSeePlusPlus
  - DiscordSRV
commands:
  sanction:
    aliases: [ss]
    description: Sert a donnee une sanction a un joueur
    permmission: sanction.use
  banrsstaff:
    permmission: sanction.banrsstaff
  staff:
    permmission: sanction.use
  spec:
    permmission: sanction.spec
  sanctionrl:
    description: Sert a reload le plugin sanction
    permmission: sanction.rl
  report:
    description: Signale un joueur