name: Build

# For each push on all branchs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'gradle'
    - uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.m2
        key: ${{ runner.os }}-gradle-cache
        restore-keys: ${{ runner.os }}-gradle-cache
    - name: Grant execute permission for all runners
      run: chmod +x gradlew install.sh
    - name: Run setup spigot script
      run: bash install.sh

    - id: build-gradle
      name: Build with Gradle
      run: ./gradlew shadowJar
      # continue even if there is an issue to save all cache
      continue-on-error: true
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: build/libs/*.jar
        name: SanctionStaff
        compression-level: 0
