name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout repo

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Upload Artifact to GitHub Action
      uses: actions/upload-artifact@v4
      with: 
        name: SanctionStaff
        path: build/libs/*.jar
